### ISSUE TITLE
Question about compiling the mod

### ISSUE THREAD

**Issue by vkethana** [farooqkz/mtbotter#1]
I was wondering how I should compile the mod. The readme says to follow the compiling instructions for minetest. Does that mean that I should `git clone` the Minetest repository, and then place `mtbotter` somewhere inside of the Minetest repository? I tried only running the `cmake` commands that the Minetest Github repository describes, but I got several errors, and I was unable to compile the code.

I am using MacOS Ventura with an Intel CPU (not an M1 chip).

Thank you for clarifying this.

**Comment by farooqkz** [comment]
Hello. I've done this project long ago and I don't remember anything about it. BTW, it's not a mod. If you need to write bots for Minetest, I suggest https://github.com/minetest-rust/mt_client
